---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cloudflare-operator/

patches:
  - path: ./default-tunnel-patch.yaml
    target:
      group: networking.cfargotunnel.com
      kind: Tunnel
      name: default-tunnel
      namespace: cloudflare-operator-system
  - target:
      group: networking.cfargotunnel.com
      kind: TunnelBinding
      name: zz-clustername-gateway
      namespace: cloudflare-operator-system
    patch: |-
      - op: replace
        path: /metadata/name
        value: zz-kubevirt-lab-1-gateway
  - path: ./tunnel-binding-gateway-patch.yaml
    target:
      group: networking.cfargotunnel.com
      kind: TunnelBinding
      name: zz-clustername-gateway
      namespace: cloudflare-operator-system
    
