kind: Secret
apiVersion: v1
metadata:
  name: grafana-credentials
stringData:
  client-id: ENC[AES256_GCM,data:LaY00rAi3e4uVQ2cUsEKMJQiJKKg,iv:XLg6I4zJFJbcmBOlIOzw1f8pgTSAfA3yC3SIes3TS6g=,tag:jotjbr5nDXsRzx/U5WOhVg==,type:str]
  client-secret: ENC[AES256_GCM,data:3NTOYvYPGyLqETtA1CrVteQGECBmPDJ1F+Fa2gWcqmk=,iv:dGSwB5w33OjHy6L/IZjixQZxXdxmzzPASXgdoBf2SXA=,tag:Z0tIC5nezhl478LTYmlJqA==,type:str]
type: Opaque
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eWtvYXBBT0NFb2U1Y0lM
        TFBjZGN6T3k5VWZNdURnNWNzQXluaG90MUFjClBjVERXdmFySkdlTW1sQngwMjhL
        ZW1ENm9FdmFvNWNPRUhuOUtkUDRqWmsKLS0tIGQzRGd4ZnhoSHM1L0o4WFBTSUc0
        UnBaa2o2eGM2aHJXZTYvN0JZa2Z5ZEUKQVJhfMElRbDSfAB2CwTRHYrshh5z3u/A
        dW086yF7dtfGMe0+eyJkYkIwxZwVf5ZHyX5dJ62sNB0zdhqxlOMUhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-02T05:17:29Z"
  mac: ENC[AES256_GCM,data:nv6TbhgT8/jo4+ngCt/YrlKOXRGKHH88LN06TQzdEYKUX+VYNybEZDUDvZEs2ufuBr+h0FDtknw+j534XC1KPPVdQwuRgtLpxfw/BeuHshgpmHyeZrGK/wj0ICKHz9QE2w++OI5hs6In/o8QJPYDPri86sqklL12GDtCifveS2c=,iv:e9ObDPznDGTc85fGdZahs0yulyjU2qQUvP+MwhhIXx8=,tag:rLQwHE3n7ligiPIqkXXQ3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
