apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  config:
    server:
      root_url: "https://grafana.isning.moe"
      enable_gzip: "true"
    log:
      mode: "console"
    auth:
      disable_login_form: "true"
    auth.generic_oauth:
      # For variables see https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#env-provider
      enabled: "true"
      name: "Logto ISNing"
      allow_sign_up: "true"
      client_id: ${AUTH_CLIENT_ID}
      client_secret: ${AUTH_CLIENT_SECRET}
      scopes: "openid email profile offline_access roles"
      email_attribute_path: email
      login_attribute_path: username
      name_attribute_path: name
      groups_attribute_path: groups
      use_refresh_token: "true"
      auth_url: "https://logto.isning.moe/oidc/auth"
      token_url: "https://logto.isning.moe/oidc/token"
      api_url: "https://logto.isning.moe/oidc/me"
      allow_assign_grafana_admin: "true"
      role_attribute_path: "contains(roles[*], 'grafana:instance_admin') && 'GrafanaAdmin' || contains(roles[*], 'grafana:admin') && 'Admin' || contains(roles[*], 'grafana:editor') && 'Editor' || contains(roles[*], 'grafana:viewer') && 'Viewer' || 'None'"
      # https://grafana.com/docs/grafana/latest/setup-grafana/configure-access/configure-authentication/generic-oauth/#configure-jwt-id-token-validation
      validate_id_token: "true"
      jwk_set_url: "https://logto.isning.moe/oidc/jwks"
      # https://grafana.com/docs/grafana/latest/setup-grafana/configure-access/configure-authentication/keycloak/#enable-single-logout
      signout_redirect_url: "https://logto.isning.moe/oidc/session/end?post_logout_redirect_uri=https://grafana.isning.moe/login"
      # TODO: Backchannel logout after grafana supports it: https://github.com/grafana/grafana/issues/84241
  # Default secret with admin credentials is disabled as the username and password are supplied externally
  disableDefaultAdminSecret: true
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: AUTH_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: grafana-credentials
                      key: client-id
                - name: AUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: grafana-credentials
                      key: client-secret
  httpRoute:
    spec:
      parentRefs:
        - name: default-gateway
      hostnames:
        - grafana.isning.moe
      rules:
        - backendRefs:
          - name: grafana-service
            port: 3000
