---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-network-addons-operator
  namespace: cluster-network-addons
spec:
  interval: 5m
  retryInterval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infra/controllers/base/kubevirt/cluster-network-addons-operator/overlay
  prune: true
  wait: true
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnao-patch-dynamic-networks-controller-ds
  namespace: cluster-network-addons
spec:
  interval: 5m
  retryInterval: 10s
  dependsOn:
    - name: cluster-network-addons-operator
      namespace: cluster-network-addons
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infra/controllers/base/kubevirt/cluster-network-addons-operator/patch-overlay
  prune: true
  wait: true
  timeout: 1m