---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-network-addons-operator
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./overlay
  prune: true
  wait: true
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnao-patch-dynamic-networks-controller-ds
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 10s
  dependsOn:
    - name: cnao
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./patch-overlay
  prune: true
  wait: true
  timeout: 1m