---
apiVersion: networkaddonsoperator.network.kubevirt.io/v1alpha1
kind: NetworkAddonsConfig
metadata:
  name: cluster
spec:
  imagePullPolicy: IfNotPresent
  # kubeMacPool: {}
  # kubeSecondaryDNS: {}
  # kubevirtIpamController: {}
  # linuxBridge: {}
  # macvtap: {}
  ovs: {} # openvswitch cni plugin
  multus: {} # required by ovs-cni
  # Manually installed and patched along with the cluster-network-addons-operator
  #multusDynamicNetworks: {}
