apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare-operator-system
type: Opaque
stringData:
  CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:iLlyJJ5GSE6ox5MeIoCX16DrxucCtDY/px/fHhwcc0VssDnVrD5m8A==,iv:hAmUL7g68GpEdBVFKlrT/zCQSPYcI0dEP95C+QreZvU=,tag:oqij0azIQcXgk3oF4ftPvA==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKb1l0Z2dxMjBsZXhES0lP
        c0RVRlhublZQYWQ3d1FOVXdrOEJWNk00YVFVClVmYkFlVWhEMlFUUnhXOFJNVEJU
        SWZLVnQ5OU1wUWVwZ3NjaUN6WjFsd2cKLS0tIFF4Tk03QnNHdlIyb2dGMWpYN2c0
        bERZeUlESmhBNFlzc0Uxb0xOeXN6R0kKEjyUyzWnaVgIyTdZQjZa6AxNXiP+tWyb
        teASPv3e7LThYiIBbF6XJWpnPbDI4Rr7y4IPnPzeXC9TiAaKQBUJgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T16:42:28Z"
  mac: ENC[AES256_GCM,data:cVSEoPWuyVp9WvLKLHdqNRoEekQWj/FnJtEn5UKqlu0Pf+RWGWVoYPZTZxR3WXETbjpB35M8jdJxQHtvLHbtW2xQR8BWrxxZqRdWtsoiKTmWr/9m/nol9QwarWJ62bcPybJJQcXJJPuPHyLwXL3ui29n8QbXwsdtCRy41OMtVdM=,iv:O36vWLCDc7/9dnoaw1uC2Tr6++XQ143e10vJt+kDiqY=,tag:gJmhG4oJefLBhYZPy6tfWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
