---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: ./cnao-patch-dynamic-networks-controller-ds.yaml
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: DaemonSet
      name: dynamic-networks-controller-ds
      namespace: cluster-network-addons
