---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # deploy monitoring stack first
  - ../../base/victoria-metrics/
  - ../../base/cert-manager/
  - ../../base/gateway-api/
  - ../../base/istio/
  - ../../base/kubevirt/

patches:
  - path: ./helmrelease-victoria-metrics.yaml
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: victoria-metrics-k8s-stack
      namespace: monitoring
