---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Use experimental install for XListenerSet.
  # - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/experimental-install.yaml
  - ./gateway-api-v1.4.1-experimental-install.yaml
