---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/adyanth/cloudflare-operator/config/default?ref=v0.13.1

namespace: cloudflare-operator-system

patches:
  - target:
      kind: Namespace
      name: cloudflare-operator-system
    patch: |
      $patch: delete
      kind: Namespace
      metadata:
        name: cloudflare-operator-system
