---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # https://github.com/adyanth/cloudflare-operator/releases/download/v0.13.1/cloudflare-operator.yaml
  - ./cloudflare-operator-0.13.1.yaml

namespace: cloudflare-operator-system

patches:
  - target:
      kind: Namespace
      name: cloudflare-operator-system
    patch: |
      $patch: delete
      kind: Namespace
      metadata:
        name: cloudflare-operator-system
