apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-minimal-bookworm
  labels:
    images.cnpg.io/date: "20260224"
    images.cnpg.io/family: postgresql
    images.cnpg.io/os: bookworm
    images.cnpg.io/publisher: cnpg.io
    images.cnpg.io/type: minimal
spec:
  images:
    - major: 13
      image: ghcr.io/cloudnative-pg/postgresql:13.22-202511100817-minimal-bookworm@sha256:02e8ffc71aec2768ca177711278d3c0e6ceb5403df5fa6d3780cd590332e3a5d
    - major: 14
      image: ghcr.io/cloudnative-pg/postgresql:14.21-202602230816-minimal-bookworm@sha256:b62fa5ea4c643e6edceab77678eff4c49dc31376cb4918910217a03d4a103f5b
    - major: 15
      image: ghcr.io/cloudnative-pg/postgresql:15.16-202602230816-minimal-bookworm@sha256:76f1c31687bcdf05114bb1599e7cbcd2762832ac1d5f3e2945714ef8965c4f28
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:16.12-202602241232-minimal-bookworm@sha256:f80433fa2277f0ac48f9aa1304c316bd5f202220f15b96eddeaa924d625b0be6
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.8-202602230816-minimal-bookworm@sha256:be618666b5f1546293c46fb6de1719d80f0963808da3c7cbce3d2aaaec52bbaa
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18.2-202602230816-minimal-bookworm@sha256:047d0b8b3dc34ad24f3a137c0903ded33afb6599496c94795739e280be0e0b21
      extensions:
        - name: pgaudit
          image:
            reference: ghcr.io/cloudnative-pg/pgaudit:18.0-202602242104-18-bookworm@sha256:e03a509eaafced93ae0bb318a97509ede91529fdc6449e335aac65df77d63a27
        - name: pgvector
          image:
            reference: ghcr.io/cloudnative-pg/pgvector:0.8.1-202602242104-18-bookworm@sha256:2f79489e5265a5e18d1be440685a4f01ac414a9304a8a7567947f9cd95e4add6
        - name: postgis
          image:
            reference: ghcr.io/cloudnative-pg/postgis-extension:3.6.2-202602242104-18-bookworm@sha256:52c2e3ffb5af6891df547a8d47643b134c804c86f19229d5b852c226d4d15ea1
          ld_library_path:
            - system
