apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-bookworm
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: bookworm
    images.cnpg.io/date: '20260226'
    images.cnpg.io/publisher: cnpg.io
spec:
  images:
  - major: 13
    image: ghcr.io/cloudnative-pg/postgresql:13.22-202511100817-standard-bookworm@sha256:e65cbf9ba18d313acde4bcdc1bc8eb636b0e005f83f23b44aba3f957ecca1e66
  - major: 14
    image: ghcr.io/cloudnative-pg/postgresql:14.22-202602261636-standard-bookworm@sha256:59ca1f09e1208bd47d09536faaf2d80042759e9307dbb1d67b40bf648d31d72d
  - major: 15
    image: ghcr.io/cloudnative-pg/postgresql:15.17-202602261636-standard-bookworm@sha256:37b7598fb322d6e6fdd10551a2c8bc78fc025645b65e1bb91bf0b3077c94f2a5
  - major: 16
    image: ghcr.io/cloudnative-pg/postgresql:16.13-202602261637-standard-bookworm@sha256:876cbaa5bb117e4feda96835b861a89c0741b91a6b2ab4419417b3228c86e3c4
  - major: 17
    image: ghcr.io/cloudnative-pg/postgresql:17.9-202602261636-standard-bookworm@sha256:5caeeccf7e9d14de9c8358c974003b51f8bfb04c3802c228768c6be173c41d9e
  - major: 18
    image: ghcr.io/cloudnative-pg/postgresql:18.3-202602261638-standard-bookworm@sha256:a37accd539046cb6ff4dbb9b82c712c85ecd5129da4e71ea1244df26dd8f7d31
