# Request a wildcard certificate for the target domain
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: i-reroute-tls
  namespace: i-reroute
spec:
  secretName: i-reroute-tls-secret
  issuerRef:
    name: letsencrypt-infra
    kind: ClusterIssuer
  dnsNames:
  - "*.i.clustername.isning.moe"
  - "*.i.isning.moe"
  - "*.i.staging.isning.moe"
