apiVersion: v1
kind: ConfigMap
metadata:
  name: i-reroute-nginx-subconfig
  namespace: i-reroute
data:
  00-prod.conf: |
    # Define Upstreams
    upstream upstream_prod_http_backend {
        server default-gateway-istio.prod.svc.cluster.local:80;
        keepalive 128;
    }

    upstream upstream_prod_https_backend {
        server default-gateway-istio.prod.svc.cluster.local:8080;
        keepalive 128;
    }

    # HTTP Server
    server {
        listen 80;
        listen [::]:80;
        server_name ~^(?<subdomain>[^.]+)\.i\.isning\.moe$;

        location / {
            proxy_set_header Host $subdomain.isning.moe;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto http;

            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
            proxy_request_buffering off;
            
            proxy_pass http://upstream_prod_http_backend;
        }
    }

    # HTTPS Server (QUIC/H3)
    server {
        listen 443 quic reuseport;
        listen 443 ssl;
        listen [::]:443 quic reuseport;
        listen [::]:443 ssl;
        http2 on;
        server_name ~^(?<subdomain>[^.]+)\.i\.isning\.moe$;

        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 1d;
        ssl_session_tickets off;

        add_header Alt-Svc 'h3=":443"; ma=86400';
        quic_retry on;
        ssl_early_data on;

        location / {
            proxy_set_header Host $subdomain.isning.moe;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;

            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
            proxy_request_buffering off;
            
            proxy_pass http://upstream_prod_https_backend;
        }
    }
  01-staging.conf: |
    # Define Upstreams
    upstream upstream_staging_http_backend {
        server default-gateway-istio.staging.svc.cluster.local:80;
        keepalive 128;
    }

    upstream upstream_staging_https_backend {
        server default-gateway-istio.staging.svc.cluster.local:8080;
        keepalive 128;
    }

    # HTTP Server
    server {
        listen 80;
        listen [::]:80;
        server_name ~^(?<subdomain>[^.]+)\.i\.staging\.isning\.moe$;

        location / {
            proxy_set_header Host $subdomain.isning.moe;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto http;

            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
            proxy_request_buffering off;
            
            proxy_pass http://upstream_staging_http_backend;
        }
    }

    # HTTPS Server (QUIC/H3)
    server {
        listen 443 quic;
        listen 443 ssl;
        listen [::]:443 quic;
        listen [::]:443 ssl;
        http2 on;
        server_name ~^(?<subdomain>[^.]+)\.i\.staging\.isning\.moe$;

        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 1d;

        add_header Alt-Svc 'h3=":443"; ma=86400';
        quic_retry on;
        ssl_early_data on;

        location / {
            proxy_set_header Host $subdomain.isning.moe;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;

            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
            proxy_request_buffering off;
            
            proxy_pass http://upstream_staging_https_backend;
        }
    }
