---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dynamic-networks-patch
  namespace: cluster-network-addons
spec:
  interval: 5m
  retryInterval: 10s
  dependsOn:
    - name: infra-controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./overlay
  prune: true
  wait: true
  timeout: 1m
