---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # ========================================
  # Install Cluster Network Addons Operator
  # ========================================
  - ./cluster-network-addons-operator-v0.101.2.yaml
  - ./cluster-network-addons-config.crd-v0.101.2.yaml
