kind: Secret
apiVersion: v1
metadata:
  name: grafana-credentials
  namespace: grafana
stringData:
  GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:9XIkaA==,iv:ItJju1GvcQ2QrqE6lAQppmqt89NZfuY9sQNlKChbiJ8=,tag:AYtzrsrfGRKdRdMO2Po7rw==,type:str]
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:gbPx9dvC+3gKCwo=,iv:cusA2YiLe05emtInvnIMBdGvoSHF6vKheWC62/dS4aM=,tag:a0hW7XupM+9eYeC24CuExA==,type:str]
type: Opaque
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUXRweElob1ArMVNpdUtT
        NnBFbE52ekI0VTgrZGFGYlJSc2NpV29UMTNVCm5FTEowcVpPdXAvdDdlcVVodmFl
        UlYxNTNkUDBLMjIvZGo4VkxPQk1LME0KLS0tIDQxQmJNK2tQSFV0VXlLS01UQTM3
        VkNPOHZGRDNoT1YxaGVFdGJLL0kyTFUKv508yKdn52vgXJT77B2mGNP0fHC6TcP2
        BL4PEAlkmUbx9I5auTT3npXMlCYaAjqZwbq0uDW6QVrr2l4hNB4OhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-24T07:32:06Z"
  mac: ENC[AES256_GCM,data:p4hrKNGTExpRkUy995j/bfERZZRHRDQqb15UCvFuUH+vfYlYhkoO4wQBQPgrhmqVSL/8ofPNPoft/iwOKI+5gyCpdlh1dws/ZDBDeyox51kUe4NIKB5gNZaQi6cp8aRHhUS8VbPUXsXzkBXvcFzIj7QlQE9yiPvSMVe303yhmsc=,iv:suLIPzFnYhHclzjRAuNOTdr4l++F03lCLkovbxmdA6o=,tag:0Ip/snDYwOAJufRXYibDew==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0

# TODO: replace with self-hosted sso OIDC
