---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cilium/
  - ../../base/secrets/
  - ./cilium

patches:
  - path: helmrelease-cilium-patch.yaml
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: cilium
      namespace: kube-system
