apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-gateway
  namespace: prod
  annotations:
    cert-manager.io/issuer: letsencrypt
spec:
  gatewayClassName: istio
  listeners:
    # Used for internal reroute
    - name: http
      protocol: HTTP
      port: 8080
      hostname: "*.isning.moe"
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.isning.moe"
      tls:
        mode: Terminate
        certificateRefs:
          - name: prod-gateway-wildcard-isning-moe-tls
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Same
  allowedListeners:
    namespaces:
      from: Same # = same namespace
---
# FIXME: Istio does not support XListenerSet yet, left it as is for future use when it supports, 80 port is not working for now, always use 443
# Move HTTP listener out of gateway to avoid auto attaching HTTPRoute to it to ensure the redirect HTTPRoute is selected
apiVersion: gateway.networking.x-k8s.io/v1alpha1
kind: XListenerSet
metadata:
  name: http-listener-set
  namespace: prod
spec:
  parentRef:
    name: default-gateway
  listeners:
    - name: http-raw
      protocol: HTTP
      port: 80
      hostname: "*.isning.moe"
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Same
---
# Redirect HTTP to HTTPS
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tls-redirect
  namespace: prod
spec:
  parentRefs:
  - name: default-gateway
    sectionName: http-raw
  hostnames:
  - "*.isning.moe"
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        port: 443
---
# Set XFF for specific listener to get correct client IP and protocol information for the services behind the gateway.
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: set-xff-for-specific-listener
  namespace: prod
spec:
  workloadSelector:
    labels:
      istio.io/gateway-name: default-gateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8080
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          use_remote_address: true
          xff_num_trusted_hops: 1
