apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-gateway
  namespace: staging
  annotations:
    cert-manager.io/issuer: letsencrypt
spec:
  gatewayClassName: istio
  listeners:
    # Used for internal reroute
    - name: http
      protocol: HTTP
      port: 8080
      hostname: "*.staging.isning.moe"
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.staging.isning.moe"
      tls:
        mode: Terminate
        certificateRefs:
          - name: staging-gateway-wildcard-staging-isning-moe-tls
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Same
  allowedListeners:
    namespaces:
      from: Same # = same namespace
---
# Move HTTP listener out of gateway to avoid auto attaching HTTPRoute to it to ensure the redirect HTTPRoute is selected
apiVersion: gateway.networking.x-k8s.io/v1alpha1
kind: XListenerSet
metadata:
  name: http-listener-set
  namespace: staging
spec:
  parentRefs:
    - name: default-gateway
      namespace: staging
  listeners:
    - name: http-raw
      protocol: HTTP
      port: 80
      hostname: "*.staging.isning.moe"
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Same
---
# Redirect HTTP to HTTPS
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tls-redirect
  namespace: staging
spec:
  parentRefs:
  - name: default-gateway
    namespace: staging
    sectionName: http-raw
  hostnames:
  - "*.staging.isning.moe"
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        port: 443

