apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-gateway
  namespace: staging
  annotations:
    cert-manager.io/issuer: letsencrypt
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.staging.isning.moe"
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.staging.isning.moe"
      tls:
        mode: Terminate
        certificateRefs:
          - name: infra-gateway-wildcard-staging-isning-moe-tls
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: All
  allowedListeners:
    namespaces:
      from: Same # = same namespace
