apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-gateway
  namespace: staging
spec:
  gatewayClassName: istio
  listeners: []
  allowedListeners:
    namespaces:
      from: Same # = same namespace
