apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: infra-gateway
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-infra
spec:
  gatewayClassName: istio
  listeners:
    # Used for internal reroute
    - name: http
      protocol: HTTP
      port: 8080
      hostname: "*.clustername.isning.moe"
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Selector
          selector:
            matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: NotIn
              values:
              - prod
              - staging
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.clustername.isning.moe"
      tls:
        mode: Terminate
        certificateRefs:
          - name: infra-gateway-wildcard-isning-moe-tls
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Selector
          selector:
            matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: NotIn
              values:
              - prod
              - staging
  allowedListeners:
    namespaces:
      from: Selector
      selector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
          - prod
          - staging
---
# Move HTTP listener out of gateway to avoid auto attaching HTTPRoute to it to ensure the redirect HTTPRoute is selected
apiVersion: gateway.networking.x-k8s.io/v1alpha1
kind: XListenerSet
metadata:
  name: http-listener-set
  namespace: kube-system
spec:
  parentRefs:
    - name: infra-gateway
      namespace: kube-system
  listeners:
    - name: http-raw
      protocol: HTTP
      port: 80
      hostname: "*.clustername.isning.moe"
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Selector
          selector:
            matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: NotIn
              values:
              - prod
              - staging
---
# Redirect HTTP to HTTPS
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tls-redirect
  namespace: kube-system
spec:
  parentRefs:
  - name: infra-gateway
    namespace: kube-system
    sectionName: http-raw
  hostnames:
  - "*.clustername.isning.moe"
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        port: 443
