---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # ========================================
  # Install KubeVirt
  # ========================================
  - ./kubevirt-operator-v1.7.0.yaml

  # ========================================
  # Install CDI(Containerized Data Importer)
  # ========================================
  - ./cdi-operator-v1.64.0.yaml
  # - ./cdi-cr-v1.xx.x.yaml # cr is created in ./infra/configs, not here

  # ========================================
  # Install Cluster Network Addons Operator
  # ========================================
  - ./cluster-network-addons-operator

patches:
  # We have create the those namespace in ./infra/namespaces,
  # so we need to delete the namespaces' creation in kubevirt-operator.yaml
  - path: delete-ns-kubevirt.yaml
  - path: delete-ns-cdi.yaml
  # - path: delete-ns-cluster-network-addons.yaml
