apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-01-secret-prod
  namespace: prod
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:BOYgp++fsZ7paSweW1UQPhFNC12YBAfm1lbgD5Q9cLxvgprB5Q+r1A==,iv:QsXgTRav2TtunFOc8xDAGDDpa416v92jsGCrJFTxCjE=,tag:VAJY3/UTdXoMH4KHVURRPQ==,type:str]
sops:
  age:
    - recipient: age167wn2qepdh87r0fqks69s0em09fkve4nrpuuxdrvgdr0dfmqpf2q08uzxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQ2hzRU92WU1nVUFqVGlC
        cy9pZlRKTUhJdzhnOHBiSlU2ZUdTdnpDZldVCnEyWUxtTE9uV0w2Q1dSTFJmSURS
        WUNmR0czdU5uYTc2bFVDaWswdzJPV2sKLS0tIG9oVll2Z3NFcjhTaVQzWjlRcUxK
        R0g1cDFYQlFpUUR6Mmw1K1Q2V0lWd1kKtqdUpAFJ5YP9Wz2Ur8iMSW4btxjM980M
        5skbyZS1kF8DiN0daCs5Gm3nggv4hzG7siaz9tCZj1IxopfK6vVB6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T14:12:06Z"
  mac: ENC[AES256_GCM,data:evlZf39ZqxYf/b9fWsDDPeCl8kaiGCGaqIjzaWQvJUtXc+2ZGQwtEHBr988/zP+lGd1mmAJE+fa7pLh5OvuDW2muYyXdTF+PvFX8yj5+y0dulvc1RO8ho2U0LgXF41I1c8sETGjhQ/4HgGInqpa0nlhHCV/pNXfXYJEb+gxBU4M=,iv:k6DfcZklWcjSV8orT9Y/ShTt59zVm9BUNGw6xh4YbS0=,tag:tlazgcbgKVnSpd+B1wYnDA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
