---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cloudflare-dns-01-secret-infra.yaml
  - ./cloudflare-dns-01-secret-prod.yaml
  - ./cloudflare-dns-01-secret-staging.yaml
  - ./issuer-isning-moe-infra.yaml
  - ./issuer-isning-moe-prod.yaml
  - ./issuer-isning-moe-staging.yaml
