---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vms
resources: []

patches:
  # add podAntiAffinity to all master nodes
  - path: ./common-patch.yaml
    target:
      group: kubevirt.io
      kind: VirtualMachine
