---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/echo/

patches:
  - target:
      group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: echo
    path: ./httproute-patch.yaml
